[build]
    command = "make build"
    functions = "functions"
    publish = "build"

[build.environment]
    GO_IMPORT_PATH = "github.com/han-so1omon/fractalooze"
    GO111MODULE = "on"

#TODO add redirects for loose coupling with vendor
